export { default as HomePage } from './page/HomePage/homePage'
export { default as RepoList } from './page/DetailUser'
export { default as NotFoundPage } from './page/NotFound'
export { default as debounceFunction } from './utils/debounceFunction'
export { default as decode } from './utils/decode'
export { default as getDataApi } from './services/getDataApi'
export { default as setClassName } from './utils/setClassName'

export { default as Modal } from './common/CreateModal/modal'

export * as GET_URL_API from './services/getUrlApi'
export * as DATE_TIME_HANDLER from './utils/formatDate'
export * as NUMBER_HANDLER from './utils/formatNumber'
export * as CALL_API_TYPE from './constant/typeCallApi'
export * as CHECK_STYLE from './utils/checkStyle'
